### ISSUE TITLE
Add filterable/searchable table for detailed view columns

### ISSUE THREAD

**Issue by Hanhula** [Hanhula/projectbrigid#18]
With the new fullDetail mode comes new capabilities. First of these should be adding more to the table (by, most likely, extending the existing articletable component). 

Ideally, I'd like to be able to search, sort, and filter on fields like wordCount, views, and likes, and I'd like to be able to access edit pages via one button.

**Comment by IbraheemHaseeb7** [comment]
hey @Hanhula 

Is this repo assignment based or should I just go ahead and start working? I couldn't find any proper instructions

**Comment by Hanhula** [comment]
Yo @IbraheemHaseeb7 ! I'm mostly creating issues right now to track things that I want to do as tasks (this one, for instance, is one that's SUPER easy for me since it's just extending the current one.. I should probably claim it as I've started on it). It's a pretty new project! 

Would be super happy to have more hands on deck with any improvements you can think of, though you'll need your own WorldAnvil app key to properly get it working - or I can put some dummy data in if that's too much of a blocker. 

I'm @hanhula on Discord as well if you wanna reach out?

**Comment by Hanhula** [comment]
Closed with #28
