### ISSUE TITLE
Add ability to search up for words in tags as well as whole tags

### ISSUE THREAD

**Issue by Catoblepon** [Hanhula/projectbrigid#25]
We can know search up the tags we have on our articles, but what if we could search up words inside the tags?

What I mean, right now, we are able to search up "low-stub-fauna" or "high-stub-fauna", but what if we could search up just the word "stub" and it makes appear articles with both tags? 
It is the way WorldAnvil's tag list bbcode works and many people probably did such as I did and made multiples tags be mixed into one (such as Satrium shows in this article <https://www.worldanvil.com/w/lothrea/a/advanced-uses-of-tags-article>)

**Comment by Hanhula** [comment]
Just updating the title of this to better fit. I think the best way of doing this would be allowing users to switch between modes here.
