### ISSUE TITLE
Articles with no tag will occasionally show the tag 'null'

### ISSUE THREAD

**Issue by Hanhula** [Hanhula/projectbrigid#3]

**Comment by Kordishal** [comment]
Most fields are null when they never had a value. So you have to assume that there might be null in most cases.

**Comment by Hanhula** [comment]
@Kordishal True, except - in most cases, when there's null, tanstack just displays nothing. Yet for some, it's reading it as a value instead and passing it in as a badge. It's kind of funny. x)
