### ISSUE TITLE
Some text comes in in the export as different characters

### ISSUE THREAD

**Issue by kaixabu** [Hanhula/projectbrigid#55]
These are exclusively the non A-Z characters (special characters for English writers, but not for other languages (Most of these are Gaelic or Middle-eastern that have been changed, btw))
[Examples.txt](https://github.com/Hanhula/projectbrigid/files/14733688/Examples.txt)

I can supply the whole export if you want or need.

**Comment by Hanhula** [comment]
Ooh, this is an encoding issue! Looks like it's not exporting in UTF-8. I'll see if I can fix that.

**Comment by Hanhula** [comment]
Alright, this should be fixed now, @kaixabu! Let me know if it doesn't - it's working on my end.

**Comment by kaixabu** [comment]
100% fixed.  Happy Dance.  You rock!
